kalapatru/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from LR.views import transporters,customers,forwardingNote,forwardingNotes,settings,dispatch,dispatches,vans
from LR.dailyreport import dailyReportView,chartView
from model_report.urls import *
from model_report import report
from stock.views import stock,upload
from LR.dailyreport import CheckEntryView
report.autodiscover()
admin.autodiscover()
print admin.site.urls
urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'kalapatru.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),


    # url(r'', include('model_report.urls')),


    url(r'^admin/', include(admin.site.urls)),
    url(r'^api/transporters/$', transporters),
    url(r'^api/forwardingNote/$', forwardingNote),
    url(r'^api/customers/$', customers),
    url(r'^api/settings/$', settings),
    url(r'^api/forwardingNotes/$', forwardingNotes),
    url(r'^api/dispatch/$', dispatch),
    url(r'^api/dispatches/$', dispatches),
    url(r'^api/vans/$', vans),
    url(r'^report/', include('model_report.urls')),
    url(r'^stock/$', stock),
    url(r'^stock/upload/$', upload),
    url(r'^dailyreport/$', dailyReportView),
    url(r'^dailyreport/chart/$', chartView),
    url(r'^dailyreport/check/$', CheckEntryView.as_view()),
)

stock/models.py
from django.db import models
from django.contrib import admin
from django import forms

from django import forms
from django.contrib import admin




CHOICES = (
    ('0', 'In'),
    ('1', 'Out'),
)

class Address(models.Model):
    label = models.CharField(max_length=250, null=True, blank=True)
    cst = models.CharField(max_length=250, null=True, blank=True)
    tin = models.CharField(max_length=250, null=True, blank=True)
    address_Line1 = models.CharField(max_length=250, null=True, blank=True)
    address_Line2 = models.CharField(max_length=250, null=True, blank=True)
    city = models.CharField(max_length=250, null=True, blank=True)
    state = models.CharField(max_length=250, null=True, blank=True)
    postal_Code = models.CharField(max_length=250, null=True, blank=True)
    phone = models.CharField(max_length=250, null=True, blank=True)
    email = models.CharField(max_length=250, null=True, blank=True)
    country = models.CharField(max_length=250, null=True, blank=True)

    def __str__(self):
        return "%s-%s" % (self.city,self.label)


admin.site.register(Address)


class Company(models.Model):
    name=models.CharField(max_length=250,null=True,blank=True)
    address=models.ManyToManyField(Address)
    def __str__(self):
        return "%s" % (self.name)


admin.site.register(Company)

class SupplyPlace(models.Model):
    name=models.CharField(max_length=250,null=True,blank=True)

    def __str__(self):
        return "%s" % (self.name)

admin.site.register(SupplyPlace)


class Commodity(models.Model):
    name=models.CharField(max_length=250,null=True,blank=True)

    def __str__(self):
        return "%s" % (self.name)

admin.site.register(Commodity)


class Stock(models.Model):
    type=models.CharField(max_length=250,choices=CHOICES)
    company=models.ForeignKey(Company)
    address=models.ForeignKey(Address)
    bill_No=models.CharField(max_length=250,null=True,blank=True)
    bill_Date=models.DateField(null=True,blank=True)
    bill_Rec_Date=models.DateField(null=True,blank=True)
    bill_Amount=models.FloatField(null=True,blank=True)
    lr_No=models.CharField(max_length=250,null=True,blank=True)
    lr_Date = models.DateField(null=True, blank=True)
    cases = models.CharField(max_length=250, null=True, blank=True)
    carriers_Name = models.CharField(max_length=250, null=True, blank=True)
    permit_No = models.CharField(max_length=250, null=True, blank=True)
    permit_Amt = models.FloatField(null=True, blank=True)
    doc_Month = models.CharField(max_length=250, null=True, blank=True)
    F_C_O=models.CharField(max_length=250, null=True, blank=True)
    date = models.DateField(null=True, blank=True)
    qrt = models.CharField(max_length=250, null=True, blank=True)
    year = models.CharField(max_length=250, null=True, blank=True)
    remarks = models.CharField(max_length=250, null=True, blank=True)
    commodity = models.ForeignKey(Commodity)


    def __str__(self):
        return "%s"%(self.company.name)


admin.site.register(Stock)

stock/views.py
from django.shortcuts import render
#from forms import StockForm
from django.contrib.auth.decorators import login_required
from models import Stock,Company,SupplyPlace,Commodity
from django.contrib import admin

import json
@login_required(login_url='/admin/login/')
def stock(request):
    groups = request.user.groups.all()
    groupList=[]
    for obj in groups:
        groupList.append(obj.name)
    usr=request.user
    if usr.is_superuser or 'stock' in groupList:
        companyObj=Company.objects.all()
        commodityObj=Commodity.objects.all()
        context={}
        context['companyObj']=companyObj
        # context['companyObjList']=json.dumps(list(companyObj))
        context['commodityObj']=commodityObj

        if request.method == 'POST':
            tp= request.POST.get('type1', None)
            stockObj=Stock()
            stockObj.type=request.POST.get('type1',None)
            stockObj.company_id=str(request.POST.get('company_Name',None))
            print str(request.POST.get('cmpAddress',None))
            stockObj.address_id=str(request.POST.get('cmpAddress',None))
            stockObj.bill_No=request.POST.get('bill_No',None)
            bill_Date = request.POST.get('bill_Date', None)
            if len(bill_Date)>4:
                stockObj.bill_Date=bill_Date
            bill_Rec_Date = request.POST.get('bill_Rec_Date', None)
            if len(bill_Rec_Date) > 4:
                stockObj.bill_Rec_Date=bill_Rec_Date
            try:
                bill_Amount = float(str(request.POST.get('bill_Amount', '')))
                stockObj.bill_Amount=bill_Amount
            except:
                pass

            stockObj.lr_No=request.POST.get('lr_No',None)
            lr_Date = request.POST.get('lr_Date', None)
            if len(lr_Date) > 4:
                stockObj.lr_Date=lr_Date
            stockObj.cases=request.POST.get('cases',None)
            stockObj.carriers_Name=request.POST.get('carriers_Name',None)
            stockObj.permit_No=request.POST.get('permit_No',None)
            try:
                permit_Amt = float(str(request.POST.get('permit_Amt', '')))
                stockObj.permit_Amt = permit_Amt
            except:
                pass
            stockObj.doc_Month=request.POST.get('doc_Month',None)
            stockObj.F_C_O=request.POST.get('F_C_O',None)
            date = request.POST.get('date', None)
            if len(date) > 4:
                stockObj.date=date
            stockObj.qrt=request.POST.get('qrt',None)
            stockObj.remarks=request.POST.get('remarks',None)
            stockObj.commodity_id=str(request.POST.get('commodity',None))
            stockObj.year=request.POST.get('year',None)
            stockObj.save()
            context['message']="Stock Added Successfully. Note down Record Id-"+str(stockObj.id)
            return render(request, 'stock.html',context)
        return render(request, 'stock.html',context)
    else:
        context={'errorCode':404,'errorMsg':'You dont have this permissions'}



def upload(request):

    if request.method == 'POST':
        fileName=request.POST.get('myfile', None)
        print fileName

    return render(request, 'uploadfile.html')

templates/base.html
{% load i18n %}<!DOCTYPE HTML>
<html>

<head>
    <title>{% block title %}{% endblock %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <style type="text/css">
      body {
        padding-top: 60px;
        padding-bottom: 40px;
      }
      .sidebar-nav {
        padding: 9px 0;
      }
      fieldset {
        float: left;
        width: 33%;
      }
      .actions {
        float: left;
        clear: both;
      }
      p.row {
        margin-left: 0px;
      }
      .caption, .caption:hover {
        font-weight: bold !important;
        background: #EEE !important;
      }
      .grouper, .grouper:hover {
        background: #333 !important;
        color: #EEE !important;
      }
      .utils {

        sheight: 70px;
        text-align: left;
      }
      .utils p {
          margin: 0;
          padding: 0;
      }
      .readthedocs {
        background: url("https://media.readthedocs.org/images/logo.png") no-repeat scroll left top transparent;
        background-color: #404750;
      }
      .travis {
        text-align: right;
      }
      #forkme {position: fixed; top: 0; right: 0; z-index: 10000;}

.nav > li > a {
    padding-bottom: 0;
  }
    </style>
        <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap.min.css">

    <!-- Optional theme -->
    <link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap-theme.min.css">

    <!-- Latest compiled and minified JavaScript -->
    <script src="//netdna.bootstrapcdn.com/bootstrap/3.0.0/js/bootstrap.min.js"></script>

    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
    {% block head_extra %}
    {% endblock %}
</head>
<body class="{% block body_class %}{% endblock %}">

    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="brand" href="/">django-model-report</a>

        </div>
      </div>
    </div>

    <div class="navbar navbar-fixed-top navbar-inverse" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">django-model-report</a>
        </div>
      </div><!-- /.container -->
    </div><!-- /.navbar -->

<div class="container">
    {% block container %}
    <div class="row">

        <div class="col-xs-6 col-sm-3 sidebar-offcanvas" id="sidebar" role="navigation">
          <div class="well sidebar-nav">
            <ul class="nav">
              <li><p class="readthedocs">
                  <a href="https://django-model-report.readthedocs.org/en/latest/" target="_blank">
                    <img src="https://media.readthedocs.org/images/logo.png">
                  </a>
                </p></li>
              <li><p class="travis">
                  <a href="https://travis-ci.org/juanpex/django-model-report" target="_blank">
                    <img src="https://travis-ci.org/juanpex/django-model-report.png" />
                  </a>
                </p></li>

              <li class="nav-header">{% trans "Report list" %}</li>
              {% block sidebar %}
              {% endblock %}
            </ul>
          </div><!--/.well -->
        </div>
        <div class="col-xs-9">
        {% block content %}
        {% endblock %}
        </div>
    </div>
    {% endblock %}
</div>

<a href="https://github.com/juanpex/django-model-report"><img style="position: fixed; top: 0; right: 0; border: 0; z-index: 10000;" src="https://s3.amazonaws.com/github/ribbons/forkme_right_orange_ff7600.png" alt="Fork me on GitHub"></a>

<script type="text/javascript">

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-36200991-1']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

</script>
</body>
</html>

templates/chart.html
<html>
<head>

<script type="text/javascript" src="https://cdn.jsdelivr.net/jquery/latest/jquery.min.js"></script>
<script type="text/javascript" src="https://cdn.jsdelivr.net/momentjs/latest/moment.min.js"></script>
<script type="text/javascript" src="https://cdn.jsdelivr.net/npm/daterangepicker/daterangepicker.min.js"></script>
<link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/npm/daterangepicker/daterangepicker.css" />


</head>
<body>
<form>
     <input name="dates">
    <select name="branch" id="branch">
  <option value="All">All</option>
        {% for i in branches %}
  <option value="{{i}}">{{ i }}</option>
        {% endfor %}
</select>
</form>
<canvas id="canvas"></canvas>
	<button hidden id="randomizeData">Randomize Data</button>
	<button hidden id="addDataset">Add Dataset</button>
	<button hidden id="removeDataset">Remove Dataset</button>
	<button hidden id="addData">Add Data</button>
	<button hidden id="removeData">Remove Data</button>
<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.3/Chart.min.js"></script>


	<script>
		var MONTHS = ['Total Card Sale', 'Total Credit Sale', 'Total Cash Sale', 'Total Sale', 'Total Credit Purchase', 'Total Cash Purchase', 'Total Purchase', 'Total Deposit', 'Total Expense', 'Total Cash In'];
		var color = Chart.helpers.color;
		window.chartColors = {
	red: 'rgb(255, 99, 132)',
	orange: 'rgb(255, 159, 64)',
	yellow: 'rgb(255, 205, 86)',
	green: 'rgb(75, 192, 192)',
	blue: 'rgb(54, 162, 235)',
	purple: 'rgb(153, 102, 255)',
	grey: 'rgb(201, 203, 207)'
};


		var randomColorGenerator = function () {
    return '#' + (Math.random().toString(16) + '0000000').slice(2, 8);
};
		var barChartData = {
			labels: ['Total Card Sale', 'Total Credit Sale', 'Total Cash Sale', 'Total Sale', 'Total Credit Purchase', 'Total Cash Purchase', 'Total Purchase', 'Total Deposit', 'Total Expense', 'Total Cash In'],
			datasets: [{
				backgroundColor: ['green','green','green','green','red','orange','red','blue','red','green'],
				borderColor: window.chartColors.grey,
				borderWidth: 1,
				data: {{ data }}
			}]

		};

		window.onload = function() {
			var ctx = document.getElementById('canvas').getContext('2d');
			ctx.canvas.height = 90;
			window.myBar = new Chart(ctx, {
				type: 'bar',
				data: barChartData,
				options: {
					responsive: true,
					legend: {
						position: 'top',
					},
					title: {
						display: true,
						text: 'Report'
					}
				}
			});

		};

		document.getElementById('randomizeData').addEventListener('click', function() {
			var zero = Math.random() < 0.2 ? true : false;
			barChartData.datasets.forEach(function(dataset) {
				dataset.data = dataset.data.map(function() {
					return zero ? 0.0 : randomScalingFactor();
				});

			});
			window.myBar.update();
		});

		var colorNames = Object.keys(window.chartColors);
		document.getElementById('addDataset').addEventListener('click', function() {
			var colorName = colorNames[barChartData.datasets.length % colorNames.length];
			var dsColor = window.chartColors[colorName];
			var newDataset = {
				label: 'Dataset ' + (barChartData.datasets.length + 1),
				backgroundColor: color(dsColor).alpha(0.5).rgbString(),
				borderColor: dsColor,
				borderWidth: 1,
				data: []
			};

			for (var index = 0; index < barChartData.labels.length; ++index) {
				newDataset.data.push(randomScalingFactor());
			}

			barChartData.datasets.push(newDataset);
			window.myBar.update();
		});

		document.getElementById('addData').addEventListener('click', function() {
			if (barChartData.datasets.length > 0) {
				var month = MONTHS[barChartData.labels.length % MONTHS.length];
				barChartData.labels.push(month);

				for (var index = 0; index < barChartData.datasets.length; ++index) {
					// window.myBar.addData(randomScalingFactor(), index);
					barChartData.datasets[index].data.push(randomScalingFactor());
				}

				window.myBar.update();
			}
		});

		document.getElementById('removeDataset').addEventListener('click', function() {
			barChartData.datasets.pop();
			window.myBar.update();
		});

		document.getElementById('removeData').addEventListener('click', function() {
			barChartData.labels.splice(-1, 1); // remove the label first

			barChartData.datasets.forEach(function(dataset) {
				dataset.data.pop();
			});

			window.myBar.update();
		});
	</script>

<script>
    $('input[name="dates"]').daterangepicker({
         ranges: {
           'Today': [moment(), moment()],
           'Yesterday': [moment().subtract(1, 'days'), moment().subtract(1, 'days')],
           'Last 7 Days': [moment().subtract(6, 'days'), moment()],
           'Last 30 Days': [moment().subtract(29, 'days'), moment()],
           'This Month': [moment().startOf('month'), moment().endOf('month')],
           'Last Month': [moment().subtract(1, 'month').startOf('month'), moment().subtract(1, 'month').endOf('month')]
        }}
    );
     $('input[name="dates"]').on('apply.daterangepicker', function(ev, picker) {
         window.location="/dailyreport/chart/?start_date="+picker.startDate.format('YYYY-MM-DD') +"&end_date=" + picker.endDate.format('YYYY-MM-DD') + "&branch=" + $("#branch").val();
  });


    </script>
</body>
</html>

templates/pickdate.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">

<script type="text/javascript" src="https://cdn.jsdelivr.net/jquery/latest/jquery.min.js"></script>
<script type="text/javascript" src="https://cdn.jsdelivr.net/momentjs/latest/moment.min.js"></script>
<script type="text/javascript" src="https://cdn.jsdelivr.net/npm/daterangepicker/daterangepicker.min.js"></script>
<link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/npm/daterangepicker/daterangepicker.css" />


</head>

    <div class="row">
         <div class="col-sm-4">
         </div>

        <div class="col-sm-4">
        <h3>Please select date range.</h3>
<form>
     <input name="dates">
</form>
        </div>
 <div class="col-sm-4">
 </div>
    </div>
<script>
    $('input[name="dates"]').daterangepicker({
         ranges: {
           'Today': [moment(), moment()],
           'Yesterday': [moment().subtract(1, 'days'), moment().subtract(1, 'days')],
           'Last 7 Days': [moment().subtract(6, 'days'), moment()],
           'Last 30 Days': [moment().subtract(29, 'days'), moment()],
           'This Month': [moment().startOf('month'), moment().endOf('month')],
           'Last Month': [moment().subtract(1, 'month').startOf('month'), moment().subtract(1, 'month').endOf('month')]
        }}
    );
     $('input[name="dates"]').on('apply.daterangepicker', function(ev, picker) {
         window.location="/dailyreport/chart/?start_date="+picker.startDate.format('YYYY-MM-DD') +"&end_date=" + picker.endDate.format('YYYY-MM-DD');
  });


    </script>
</body>
</html>

templates/stock.html
<!DOCTYPE html>
<html lang="en-us" >
<head>
<title>Change stock | Django site admin</title>
<link rel="stylesheet" type="text/css" href="/static/admin/css/base.css" />
<link rel="stylesheet" type="text/css" href="/static/admin/css/forms.css" />
<!--[if lte IE 7]><link rel="stylesheet" type="text/css" href="/static/admin/css/ie.css" /><![endif]-->

<script type="text/javascript">window.__admin_media_prefix__ = "/static/admin/";</script>
<script type="text/javascript">window.__admin_utc_offset__ = "0";</script>

<script type="text/javascript" src="/admin/jsi18n/"></script>
<script type="text/javascript" src="/static/admin/js/core.js"></script>
<script type="text/javascript" src="/static/admin/js/admin/RelatedObjectLookups.js"></script>
<script type="text/javascript" src="/static/admin/js/jquery.js"></script>
<script type="text/javascript" src="/static/admin/js/jquery.init.js"></script>
<script type="text/javascript" src="/static/admin/js/actions.js"></script>
<script type="text/javascript" src="/static/admin/js/calendar.js"></script>
<script type="text/javascript" src="/static/admin/js/admin/DateTimeShortcuts.js"></script>

<meta name="robots" content="NONE,NOARCHIVE" />

    <script>
        function funckDate(id)
        {
            var monthDict={'01':"Jan",'02':"Feb",'03':"Mar",'04':"Apr",'05':"May",'06':"Jun",'07':"Jul",'08':"Aug",'09':"Sept",'10':"Oct",'11':"Nov",'12':"Dec"}
            var value=document.getElementById(id).value;
            var dateArray=value.split('-')
            var year=dateArray[0]
            var month=dateArray[1]
            var day=dateArray[2]
            document.getElementById('id_doc_Month').value=monthDict[month]+" "+year;
            document.getElementById('id_year').value=year;
            return false;

        }
        function hideme(id)
        {
            document.getElementById(id).style.display='none';
            return false;
        }

    </script>
</head>


<body class=" app-stock model-stock change-form">

<!-- Container -->
<div id="container">


    <!-- Header -->
    <div id="header">
        <div id="branding">

<h1 id="site-name"><a href="/admin/">Django administration</a></h1>

        </div>

        <div id="user-tools">

                Welcome,
                <strong>admin</strong>.





                <a href="/admin/password_change/">Change password</a> /

                <a href="/admin/logout/">Log out</a>

        </div>


    </div>
    <!-- END Header -->

<div class="breadcrumbs">
<a href="/admin/">Home</a>
</div>







    <!-- Content -->
    <div id="content" class="colM">

<style>
    .alert-success {
    background-image: linear-gradient(to bottom, #dff0d8 0px, #6de50e 100%);
    background-repeat: repeat-x;
    border-color: #6fdb1f;
        padding: 10px;
}
</style>
        {% if message %}
    <div  id="sucsessDiv" class="alert alert-success fade in" onclick="return hideme('sucsessDiv')">

        <a href="#" class="close" data-dismiss="alert">&times;</a>

        <strong>Success! {{ message }}</strong>

    </div>
    {% endif %}

        <h1>Change stock</h1>
        <div id="content-main">


  <ul class="object-tools">

    <li>

        <a href="/admin/stock/stock/1/history/" class="historylink">History</a>
    </li>


  </ul>


<form name="stockfrm" action="/stock/" method="post" id="stock_form" novalidate>
<div>
{% csrf_token %}






  <fieldset class="module aligned ">



        <div class="form-row field-type">


                <div>


                        <label class="required" for="id_type">Type:</label>
<input type="radio" name="type1" value="0"  checked="checked"> In
<input type="radio" name="type1" value="1"> Out



                </div>

        </div>


  <script>

                    var cmpObj= {}

                    {% for cmp in companyObj %}

                            cmpObj["{{cmp.id}}"] =

                            [{% for add in cmp.address.all %}

                                {
                                    id: "{{ add.id|escapejs }}",
                                    label: "{{ add.city|escapejs }}"+"--"+"{{add.label|escapejs}}"
                                },



                            {% endfor %}]


                    {% endfor %}

                    function getAddress()
                        {
                            var index=document.getElementById('company_Name_id').value;
                            cmpAdrObj=cmpObj[index]
{#                            console.log(cmpAdrObj[0]);#}
                            var selectList = document.getElementById("mySelect1");
                            var i;
                            for(i = selectList.options.length - 1 ; i >= 0 ; i--)
                            {
                                selectList.remove(i);
                            }
                            for (var i = 0; i < cmpAdrObj.length; i++)
                            {

                                console.log(cmpAdrObj[i].id);
                                var option = document.createElement("option");
                                option.value = cmpAdrObj[i].id;
                                option.text = cmpAdrObj[i].label;
                                selectList.appendChild(option);
                            }

                        return false;

                        }
                </script>


        <div class="form-row field-company_Name">
                <div>

                        <label for="id_company_Name">Company Name:</label>
                                            <select  id='company_Name_id' name="company_Name" onchange="return getAddress()">
				<option value="">------</option>
                                {% for obj in companyObj  %}
                                    <option value="{{ obj.id }}">{{ obj }}</option>
                                {% endfor %}
                            </select>
                </div>
        </div>


        <div class="form-row field-supply_Place" >
               <div>
                        <label for="id_company_add">Company Address:</label>
                        <select  id='mySelect1' name="cmpAddress">
                        </select>
                </div>

        </div>

        <div class="form-row field-bill_No">


                <div>


                        <label for="id_bill_No">Bill No:</label>

                            <input class="vTextField" id="id_bill_No" maxlength="250" name="bill_No" type="text" />



                </div>

        </div>

        <div class="form-row field-bill_Date">


                <div>


                        <label for="id_bill_Date">Bill Date:</label>

                            <input class="vDateField" id="id_bill_Date" name="bill_Date" size="10" type="text" onfocus="return funckDate('id_bill_Date')"/>



                </div>

        </div>

        <div class="form-row field-bill_Rec_Date">


                <div>


                        <label for="id_bill_Rec_Date">Bill Rec Date:</label>

                            <input class="vDateField" id="id_bill_Rec_Date" name="bill_Rec_Date" size="10" type="text" />



                </div>

        </div>

        <div class="form-row field-bill_Amount">


                <div>


                        <label for="id_bill_Amount">Bill Amount:</label>

                            <input id="id_bill_Amount" name="bill_Amount" step="any" type="number" />



                </div>

        </div>

        <div class="form-row field-lr_No">


                <div>


                        <label for="id_lr_No">Lr No:</label>

                            <input class="vTextField" id="id_lr_No" maxlength="250" name="lr_No" type="text" />



                </div>

        </div>

        <div class="form-row field-lr_Date">


                <div>


                        <label for="id_lr_Date">Lr Date:</label>

                            <input class="vDateField" id="id_lr_Date" name="lr_Date" size="10" type="text" />



                </div>

        </div>

        <div class="form-row field-cases">


                <div>


                        <label for="id_cases">Cases:</label>

                            <input class="vTextField" id="id_cases" maxlength="250" name="cases" type="text" />



                </div>

        </div>

        <div class="form-row field-carriers_Name">


                <div>


                        <label for="id_carriers_Name">Carriers Name:</label>

                            <input class="vTextField" id="id_carriers_Name" maxlength="250" name="carriers_Name" type="text" />



                </div>

        </div>

        <div class="form-row field-permit_No">


                <div>


                        <label for="id_permit_No">Permit No:</label>

                            <input class="vTextField" id="id_permit_No" maxlength="250" name="permit_No" type="text" />



                </div>

        </div>

        <div class="form-row field-permit_No">


                <div>


                        <label for="id_permit_AmtLb">Permit Ammount:</label>

                            <input class="vTextField" id="id_permit_Amt" maxlength="250" name="permit_Amt" type="text" />



                </div>

        </div>


        <div class="form-row field-doc_Month">


                <div>


                        <label for="id_doc_Month">Doc Month:</label>

                            <input class="vTextField" id="id_doc_Month" maxlength="250" name="doc_Month" type="text" />



                </div>

        </div>

        <div class="form-row field-F_C_O">


                <div>


                        <label for="id_F_C_O">F C O:</label>

                            <input class="vTextField" id="id_F_C_O" maxlength="250" name="F_C_O" type="text" />



                </div>

        </div>

        <div class="form-row field-date">


                <div>


                        <label for="id_date">Date:</label>

                            <input class="vDateField" id="id_date" name="date" size="10" type="text" />



                </div>

        </div>

        <div class="form-row field-qrt">


                <div>


                        <label for="id_qrt">Qrt:</label>

                            <input class="vTextField" id="id_qrt" maxlength="250" name="qrt" type="text" />



                </div>

        </div>

        <div class="form-row field-year">


                <div>


                        <label for="id_year">Year:</label>

                            <input class="vTextField" id="id_year" maxlength="250" name="year" type="text" />



                </div>

        </div>

        <div class="form-row field-remarks">


                <div>


                        <label for="id_remarks">Remarks:</label>

                            <input class="vTextField" id="id_remarks" maxlength="250" name="remarks" type="text" />



                </div>

        </div>

        <div class="form-row field-commodity">


                <div>


                        <label for="id_commodity">Commodity:</label>
                            <select name="commodity">
                                {% for obj in commodityObj  %}
                                    <option value="{{ obj.id }}">{{ obj }}</option>
                                {% endfor %}
                            </select>
                            <!--<input class="vTextField" id="id_commodity" maxlength="250" name="commodity" type="text" />-->



                </div>

        </div>

</fieldset>













<div class="submit-row">
<input type="button" value="Save" onclick="submitForm()" hidefocus="true" tabindex="-1" class="default" name="_save" />


    <p class="deletelink-box"><a href="/admin/stock/stock/1/delete/" class="deletelink">Delete</a></p>



</div>






<script type="text/javascript">
(function($) {
    var field;


})(django.jQuery);

    function submitForm(){
       document.getElementById('stock_form').submit()
    }
</script>


</div>
</form></div>


        <br class="clear" />
    </div>
    <!-- END Content -->

    <div id="footer"></div>
</div>
<!-- END Container -->

</body>
</html>